name: qamp_linux
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0=openblas
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - ncurses=6.5
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openjpeg=2.5.2
  - openssl=3.0.17
  - packaging=25.0
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pyparsing=3.2.0
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - readline=8.3
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tornado=6.5.1
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autoray==0.7.2
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - diastatic-malt==2.15.2
      - dill==0.4.0
      - gast==0.6.0
      - idna==3.10
      - joblib==1.5.2
      - kagglehub==0.3.13
      - llvmlite==0.45.1
      - mpmath==1.3.0
      - networkx==3.5
      - numba==0.62.1
      - ordered-set==4.1.0
      - pandas==2.3.3
      - pennylane==0.42.3
      - pennylane-lightning==0.42.0
      - psutil==7.1.0
      - pylatex==1.4.2
      - pylatexenc==2.10
      - pytz==2025.2
      - pyyaml==6.0.3
      - qiskit==1.4.5
      - qiskit-aer==0.17.2
      - qiskit-algorithms==0.4.0
      - qiskit-machine-learning==0.8.4
      - requests==2.32.5
      - rustworkx==0.17.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scipy-openblas32==0.3.30.0.2
      - seaborn==0.13.2
      - stevedore==5.5.0
      - symengine==0.13.0
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
